name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps: 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        uses: docker/compose-action@v2

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker  

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter
        run: docker-compose run --rm app sh -c "flake8"
