name: Checks

on: [push, pull_request]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
       
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Ensure Docker is running
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2    

    - name: Run tests
      run: docker-compose run --rm app sh -c "python manage.py test"